use crate::types::Song;

pub fn get_initial_catalog() -> Vec<Song> {
    vec![
        Song {
            id: "gmm_001".to_string(),
            code: "10001".to_string(),
            title: "รักแล้วยอมได้".to_string(),
            artist: "แช่ม แช่มรัมย์".to_string(),
            youtube_id: "inGSjouS77g".to_string(),
            guide_video_id: Some("inGSjouS77g".to_string()),
            duration_secs: 220,
            intro_skip_secs: 13,
            category: "Luk Thung".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_002".to_string(),
            code: "10002".to_string(),
            title: "ปลายทางของความคิดถึง".to_string(),
            artist: "ตั๊กแตน ชลดา".to_string(),
            youtube_id: "0cq9nSoPGZo".to_string(),
            guide_video_id: Some("0cq9nSoPGZo".to_string()),
            duration_secs: 235,
            intro_skip_secs: 13,
            category: "Luk Thung".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_003".to_string(),
            code: "10003".to_string(),
            title: "นกหลงรัง".to_string(),
            artist: "เสือ ธนพล".to_string(),
            youtube_id: "qq_pRBQjrSg".to_string(),
            guide_video_id: Some("qq_pRBQjrSg".to_string()),
            duration_secs: 260,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_004".to_string(),
            code: "10004".to_string(),
            title: "รักไม่ไหวแล้วโว้ย".to_string(),
            artist: "โจอี้ ภูวศิษฐ์".to_string(),
            youtube_id: "r1crPncm5aE".to_string(),
            guide_video_id: Some("t76_H313m7A".to_string()),
            duration_secs: 215,
            intro_skip_secs: 13,
            category: "Modern".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_005".to_string(),
            code: "10005".to_string(),
            title: "ไม่มีครั้งสุดท้าย".to_string(),
            artist: "มิ้น อรรถวดี".to_string(),
            youtube_id: "p5sPRujGdqM".to_string(),
            guide_video_id: None,
            duration_secs: 240,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_006".to_string(),
            code: "10006".to_string(),
            title: "ไปอยู่ที่ไหนมา".to_string(),
            artist: "โอ๊ค สมิทธิ์".to_string(),
            youtube_id: "c0tYoAQm9_k".to_string(),
            guide_video_id: None,
            duration_secs: 228,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_007".to_string(),
            code: "10007".to_string(),
            title: "ดาวเสาร์ (Saturn)".to_string(),
            artist: "LULA".to_string(),
            youtube_id: "RDTWvDDn0Bk".to_string(),
            guide_video_id: Some("RDTWvDDn0Bk".to_string()),
            duration_secs: 230,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_008".to_string(),
            code: "10008".to_string(),
            title: "บ่กล้าบอกไผ".to_string(),
            artist: "ไหมไทย ใจตะวัน".to_string(),
            youtube_id: "pZctcALD-0U".to_string(),
            guide_video_id: None,
            duration_secs: 250,
            intro_skip_secs: 13,
            category: "Luk Thung".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_009".to_string(),
            code: "10009".to_string(),
            title: "ไม่รักแต่ไม่ลืม".to_string(),
            artist: "แอม เสาวลักษณ์".to_string(),
            youtube_id: "iyEDnU0AUQs".to_string(),
            guide_video_id: None,
            duration_secs: 245,
            intro_skip_secs: 13,
            category: "Classic 90s".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_010".to_string(),
            code: "10010".to_string(),
            title: "น้ำใสใจจริง".to_string(),
            artist: "ปราโมทย์ วิเลปะนะ".to_string(),
            youtube_id: "Xp8D5lRYf-c".to_string(),
            guide_video_id: None,
            duration_secs: 225,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_011".to_string(),
            code: "10011".to_string(),
            title: "I've Got You".to_string(),
            artist: "PECK PALITCHOKE".to_string(),
            youtube_id: "GEvqq6YbKfQ".to_string(),
            guide_video_id: None,
            duration_secs: 210,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_012".to_string(),
            code: "10012".to_string(),
            title: "นางร้าย".to_string(),
            artist: "Pancake".to_string(),
            youtube_id: "iF64rmmKJaY".to_string(),
            guide_video_id: None,
            duration_secs: 232,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_013".to_string(),
            code: "10013".to_string(),
            title: "oasis".to_string(),
            artist: "Atom ชนกันต์ feat. D Gerrard".to_string(),
            youtube_id: "_NzrFynYFJU".to_string(),
            guide_video_id: Some("_NzrFynYFJU".to_string()),
            duration_secs: 240,
            intro_skip_secs: 13,
            category: "Modern".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_014".to_string(),
            code: "10014".to_string(),
            title: "ทุกนาทีให้เธอ".to_string(),
            artist: "ไอซ์ ศรัณยู".to_string(),
            youtube_id: "Kyx2Jbm5bFg".to_string(),
            guide_video_id: None,
            duration_secs: 218,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_015".to_string(),
            code: "10015".to_string(),
            title: "ลุคBAD SADบ่อย".to_string(),
            artist: "MUSSEAW".to_string(),
            youtube_id: "ouzdahsP7tM".to_string(),
            guide_video_id: None,
            duration_secs: 205,
            intro_skip_secs: 13,
            category: "Modern".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_016".to_string(),
            code: "10016".to_string(),
            title: "ลืมหน่อยก็ไม่ได้".to_string(),
            artist: "เอิร์น สุรัตน์ติกานต์".to_string(),
            youtube_id: "9zndDpiItas".to_string(),
            guide_video_id: None,
            duration_secs: 238,
            intro_skip_secs: 13,
            category: "Luk Thung".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_017".to_string(),
            code: "10017".to_string(),
            title: "เพื่อนกันไม่ทำแบบนี้".to_string(),
            artist: "PRINCE".to_string(),
            youtube_id: "34ApHPRuu0I".to_string(),
            guide_video_id: None,
            duration_secs: 226,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_018".to_string(),
            code: "10018".to_string(),
            title: "ความจำสั้น".to_string(),
            artist: "ต๊อง วิตติวัต".to_string(),
            youtube_id: "gLADl-lcLIA".to_string(),
            guide_video_id: None,
            duration_secs: 242,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_019".to_string(),
            code: "10019".to_string(),
            title: "ชีวิตที่เคยมีเรา".to_string(),
            artist: "The Mousses".to_string(),
            youtube_id: "-ZgREu-tU9Y".to_string(),
            guide_video_id: Some("-ZgREu-tU9Y".to_string()),
            duration_secs: 250,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_020".to_string(),
            code: "10020".to_string(),
            title: "ยิ่งใกล้...ยิ่งไกล".to_string(),
            artist: "เจนนิเฟอร์ คิ้ม".to_string(),
            youtube_id: "mOKoOVynxxM".to_string(),
            guide_video_id: None,
            duration_secs: 248,
            intro_skip_secs: 13,
            category: "Classic 90s".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_021".to_string(),
            code: "10021".to_string(),
            title: "เปียกอับชื้น".to_string(),
            artist: "Buddha Bless".to_string(),
            youtube_id: "F32jJgDyyAI".to_string(),
            guide_video_id: Some("F32jJgDyyAI".to_string()),
            duration_secs: 230,
            intro_skip_secs: 13,
            category: "Modern".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_022".to_string(),
            code: "10022".to_string(),
            title: "ห้ามใจ".to_string(),
            artist: "หนูนา หนึ่งธิดา".to_string(),
            youtube_id: "s8GIehbfun8".to_string(),
            guide_video_id: None,
            duration_secs: 220,
            intro_skip_secs: 13,
            category: "Pop".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_023".to_string(),
            code: "10023".to_string(),
            title: "CLOCK".to_string(),
            artist: "Supersub".to_string(),
            youtube_id: "MuHgMFxwH7U".to_string(),
            guide_video_id: None,
            duration_secs: 236,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_024".to_string(),
            code: "10024".to_string(),
            title: "สาว ตจว. ม.ราชภัฏ".to_string(),
            artist: "จั๊กจั่น วันวิสา".to_string(),
            youtube_id: "gVWKW150UK8".to_string(),
            guide_video_id: None,
            duration_secs: 245,
            intro_skip_secs: 13,
            category: "Luk Thung".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        // Legendary Rock Anthems with Guide Vocal
        Song {
            id: "gmm_025".to_string(),
            code: "10025".to_string(),
            title: "เล่นของสูง".to_string(),
            artist: "Big Ass".to_string(),
            youtube_id: "4k3v7_XG2Xk".to_string(),
            guide_video_id: Some("c21d8jDskf8".to_string()),
            duration_secs: 248,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_026".to_string(),
            code: "10026".to_string(),
            title: "คุกเข่า".to_string(),
            artist: "COCKTAIL".to_string(),
            youtube_id: "9aCUDQ8SPcA".to_string(),
            guide_video_id: Some("n_s_XlO5Q3c".to_string()),
            duration_secs: 260,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_028".to_string(),
            code: "10028".to_string(),
            title: "เธอ (Tur)".to_string(),
            artist: "COCKTAIL".to_string(),
            youtube_id: "Nlr1jPW6LZ4".to_string(),
            guide_video_id: Some("Nlr1jPW6LZ4".to_string()),
            duration_secs: 268,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_029".to_string(),
            code: "10029".to_string(),
            title: "คู่ชีวิต (Koo-Chee-Wit)".to_string(),
            artist: "COCKTAIL".to_string(),
            youtube_id: "mMRkEh6Z6vE".to_string(),
            guide_video_id: Some("mMRkEh6Z6vE".to_string()),
            duration_secs: 335,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_030".to_string(),
            code: "10030".to_string(),
            title: "ดึงดัน (Dueng-Dun)".to_string(),
            artist: "COCKTAIL x ตั๊ก ศิริพร".to_string(),
            youtube_id: "7Bima2M9xy4".to_string(),
            guide_video_id: Some("7Bima2M9xy4".to_string()),
            duration_secs: 250,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_031".to_string(),
            code: "10031".to_string(),
            title: "เธอทำให้ฉันเสียใจ".to_string(),
            artist: "COCKTAIL".to_string(),
            youtube_id: "Ekllc9Km16U".to_string(),
            guide_video_id: Some("Ekllc9Km16U".to_string()),
            duration_secs: 254,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_032".to_string(),
            code: "10032".to_string(),
            title: "ฉันร้องไห้เป็นหมื่นครั้งเพื่อมาเจอเธอ".to_string(),
            artist: "COCKTAIL".to_string(),
            youtube_id: "ty_8P3aHmuo".to_string(),
            guide_video_id: Some("ty_8P3aHmuo".to_string()),
            duration_secs: 275,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        Song {
            id: "gmm_033".to_string(),
            code: "10033".to_string(),
            title: "ทำดีไม่เคยจำ".to_string(),
            artist: "COCKTAIL".to_string(),
            youtube_id: "Km8J1H41sFk".to_string(),
            guide_video_id: Some("Km8J1H41sFk".to_string()),
            duration_secs: 248,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: false,
        },
        Song {
            id: "gmm_027".to_string(),
            code: "10027".to_string(),
            title: "วัดใจ".to_string(),
            artist: "Silly Fools".to_string(),
            youtube_id: "X5Zq7eU3xY8".to_string(),
            guide_video_id: Some("1-m9K2g3P_E".to_string()),
            duration_secs: 255,
            intro_skip_secs: 13,
            category: "Rock".to_string(),
            channel: "GMM Karaoke".to_string(),
            is_favorite: true,
        },
        // Whattheduck Official Karaoke Catalog
        Song {
            id: "wtd_001".to_string(),
            code: "20001".to_string(),
            title: "ที่คั่นหนังสือ (Sometimes)".to_string(),
            artist: "BOWKYLION Ft. NONT TANONT".to_string(),
            youtube_id: "xmyqhV0f9Go".to_string(),
            guide_video_id: Some("xmyqhV0f9Go".to_string()),
            duration_secs: 242,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: true,
        },
        Song {
            id: "wtd_002".to_string(),
            code: "20002".to_string(),
            title: "วาดไว้ (recall)".to_string(),
            artist: "BOWKYLION".to_string(),
            youtube_id: "Zzfu7_4NTig".to_string(),
            guide_video_id: Some("Zzfu7_4NTig".to_string()),
            duration_secs: 250,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: true,
        },
        Song {
            id: "wtd_003".to_string(),
            code: "20003".to_string(),
            title: "กำแพงหัวใจ (Heartwall)".to_string(),
            artist: "Mirrr".to_string(),
            youtube_id: "-rP1pLP5a2U".to_string(),
            guide_video_id: Some("-rP1pLP5a2U".to_string()),
            duration_secs: 238,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: true,
        },
        Song {
            id: "wtd_004".to_string(),
            code: "20004".to_string(),
            title: "พิจารณา (Consider)".to_string(),
            artist: "Musketeers Ft. MAIYARAP".to_string(),
            youtube_id: "dwU0WTiItio".to_string(),
            guide_video_id: Some("dwU0WTiItio".to_string()),
            duration_secs: 245,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: false,
        },
        Song {
            id: "wtd_005".to_string(),
            code: "20005".to_string(),
            title: "เพลงรักเพลงแรก (Blooming)".to_string(),
            artist: "LANDOKMAI".to_string(),
            youtube_id: "V8K_pA72RPQ".to_string(),
            guide_video_id: Some("V8K_pA72RPQ".to_string()),
            duration_secs: 230,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: true,
        },
        Song {
            id: "wtd_006".to_string(),
            code: "20006".to_string(),
            title: "รู้กันแค่นี้ (mint)".to_string(),
            artist: "BOWKYLION".to_string(),
            youtube_id: "RkdFRLJEcqM".to_string(),
            guide_video_id: Some("RkdFRLJEcqM".to_string()),
            duration_secs: 215,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: false,
        },
        Song {
            id: "wtd_007".to_string(),
            code: "20007".to_string(),
            title: "จำเก่ง".to_string(),
            artist: "F.HERO x Tilly Birds".to_string(),
            youtube_id: "6rn0nrzuhCo".to_string(),
            guide_video_id: Some("6rn0nrzuhCo".to_string()),
            duration_secs: 260,
            intro_skip_secs: 0,
            category: "Modern".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: true,
        },
        Song {
            id: "wtd_008".to_string(),
            code: "20008".to_string(),
            title: "ทีละน้อย (little by little)".to_string(),
            artist: "Hers".to_string(),
            youtube_id: "lpWA9D_CmPQ".to_string(),
            guide_video_id: Some("lpWA9D_CmPQ".to_string()),
            duration_secs: 228,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: false,
        },
        Song {
            id: "wtd_009".to_string(),
            code: "20009".to_string(),
            title: "Melbourne".to_string(),
            artist: "Morvasu Ft. TangBadVoice".to_string(),
            youtube_id: "KlqalFA9BzA".to_string(),
            guide_video_id: Some("KlqalFA9BzA".to_string()),
            duration_secs: 210,
            intro_skip_secs: 0,
            category: "Modern".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: false,
        },
        Song {
            id: "wtd_010".to_string(),
            code: "20010".to_string(),
            title: "ดอกไม้ที่รอฝน (spring)".to_string(),
            artist: "THE TOYS x NONT TANONT".to_string(),
            youtube_id: "EUzAdgsu4Eg".to_string(),
            guide_video_id: Some("EUzAdgsu4Eg".to_string()),
            duration_secs: 252,
            intro_skip_secs: 0,
            category: "Indie".to_string(),
            channel: "Whattheduck".to_string(),
            is_favorite: true,
        },
    ]
}

pub fn get_categories() -> Vec<&'static str> {
    vec!["All", "Rock", "Pop", "Indie", "Modern", "Luk Thung", "Classic 90s"]
}
